(ns tango.export-tests
  (:require [clojure.test :refer :all]
            [clj-time.core :as tc]
            [clj-time.coerce :as tcr]
            [tango.export :as e]
            [tango.test-utils :as u]
            [tango.expected.expected-small-result :as esr]
            ))
(def expected-xml "<?xml version=\"1.0\" encoding=\"UTF-8\"?><DancePerfect Version=\"4.1\"><CompData NameOnNumberSign=\"1\" RadomHeats=\"1\" CourierFont=\"NSimSun\" ChineseFonts=\"1\" SkipAdjLetter=\"1\" SameHeatAllDances=\"1\" RandomHeats=\"1\" HeatText=\"1\" ClubOnNumberSign=\"1\" PreView=\"1\" PrinterSelectPaper=\"1\" Date=\"2014-11-22\" AdjOrderFinal=\"1\" Name=\"TurboMegatävling\" AdjOrderOther=\"1\" Place=\"THUNDERDOME\" ArialFont=\"SimSun\" Org=\"\"></CompData><AdjPanelList><AdjList Qty=\"3\"><Adjudicator Seq=\"0\" Name=\"Anders\" Country=\"Sweden\"></Adjudicator><Adjudicator Seq=\"1\" Name=\"Bertil\" Country=\"\"></Adjudicator><Adjudicator Seq=\"2\" Name=\"Cesar\" Country=\"\"></Adjudicator></AdjList><PanelList Qty=\"30\"><Panel Seq=\"0\" Qty=\"2\"><PanelAdj Seq=\"0\" AdjNumber=\"0\"></PanelAdj><PanelAdj Seq=\"1\" AdjNumber=\"1\"></PanelAdj></Panel><Panel Seq=\"1\" Qty=\"3\"><PanelAdj Seq=\"0\" AdjNumber=\"0\"></PanelAdj><PanelAdj Seq=\"1\" AdjNumber=\"1\"></PanelAdj><PanelAdj Seq=\"2\" AdjNumber=\"2\"></PanelAdj></Panel><Panel Seq=\"2\" Qty=\"2\"><PanelAdj Seq=\"0\" AdjNumber=\"1\"></PanelAdj><PanelAdj Seq=\"1\" AdjNumber=\"2\"></PanelAdj></Panel><Panel Seq=\"3\" Qty=\"0\"></Panel><Panel Seq=\"4\" Qty=\"0\"></Panel><Panel Seq=\"5\" Qty=\"0\"></Panel><Panel Seq=\"6\" Qty=\"0\"></Panel><Panel Seq=\"7\" Qty=\"0\"></Panel><Panel Seq=\"8\" Qty=\"0\"></Panel><Panel Seq=\"9\" Qty=\"0\"></Panel><Panel Seq=\"10\" Qty=\"0\"></Panel><Panel Seq=\"11\" Qty=\"0\"></Panel><Panel Seq=\"12\" Qty=\"0\"></Panel><Panel Seq=\"13\" Qty=\"0\"></Panel><Panel Seq=\"14\" Qty=\"0\"></Panel><Panel Seq=\"15\" Qty=\"0\"></Panel><Panel Seq=\"16\" Qty=\"0\"></Panel><Panel Seq=\"17\" Qty=\"0\"></Panel><Panel Seq=\"18\" Qty=\"0\"></Panel><Panel Seq=\"19\" Qty=\"0\"></Panel><Panel Seq=\"20\" Qty=\"0\"></Panel><Panel Seq=\"21\" Qty=\"0\"></Panel><Panel Seq=\"22\" Qty=\"0\"></Panel><Panel Seq=\"23\" Qty=\"0\"></Panel><Panel Seq=\"24\" Qty=\"0\"></Panel><Panel Seq=\"25\" Qty=\"0\"></Panel><Panel Seq=\"26\" Qty=\"0\"></Panel><Panel Seq=\"27\" Qty=\"0\"></Panel><Panel Seq=\"28\" Qty=\"0\"></Panel><Panel Seq=\"29\" Qty=\"0\"></Panel></PanelList></AdjPanelList><ClassList><Class Seq=\"0\" Name=\"Hiphop Singel Star B\" AdjPanel=\"1\"><StartList Qty=\"3\"><Couple Seq=\"0\" Number=\"30\" Name=\"Rulle Trulle\" Club=\"Sinus\" License=\"\"></Couple><Couple Seq=\"1\" Number=\"31\" Name=\"Hush Bush\" Club=\"Zilson\" License=\"\"></Couple><Couple Seq=\"2\" Number=\"32\" Name=\"Banana Hamock\" Club=\"Zzzz\" License=\"\"></Couple></StartList></Class><Class Seq=\"1\" Name=\"Hiphop Singel Star J Fl\" AdjPanel=\"\"><StartList Qty=\"2\"><Couple Seq=\"0\" Number=\"20\" Name=\"Ringo Stingo\" Club=\"Kapangg\" License=\"\"></Couple><Couple Seq=\"1\" Number=\"21\" Name=\"Greve Turbo\" Club=\"OOoost\" License=\"\"></Couple></StartList></Class></ClassList></DancePerfect>")
(deftest test-export
  (testing "Export from test data"
    (is (= expected-xml (e/export esr/expected-small-example)))))

